### ISSUE TITLE
Fix logging

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping#178]
> this.logger.error(`failed to find a correct value for a filed "${field}"`, {field, sources});

The meta argument isn't in the output right now.

**Comment by patrykcieszkowski** [comment]
It isn't, but I'm not convinced it should. We should probably attach whatever is necessary to render within the error message.

```
[2022-07-28 17:14:36] [DEBUG] [1061621] [ws:error] failed to collect probe metadata ({"info":{"socketId":"T2zbnQEj1jgRpN1uAAAF"},"stack":"Error: failed to collect probe metadata\n    at file:///home/patryk/projects/globalping/api/dist/lib/ws/middleware/probe-metadata.js:18:15\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Array.<anonymous> (file:///home/patryk/projects/globalping/api/dist/lib/ws/helper/error-handler.js:8:9)"})

[2022-07-28 17:14:36] [ERROR] [1061621] [geoip] failed to find a correct value for a filed "normalizedCity" ({"field":"normalizedCity","sources":[{"continent":"NA","state":"CA","country":"US","city":"San Jose","normalizedCity":"san jose","asn":6939,"latitude":37.3394,"longitude":-121.895,"network":"Hurricane Electric LLC","normalizedNetwork":"hurricane electric llc","provider":"ipinfo"},{"continent":"NA","country":"US","state":"CA","city":"Burlingame","normalizedCity":"burlingame","asn":6939,"latitude":37.5659,"longitude":-122.3661,"network":"Ether Web Network","normalizedNetwork":"ether web network","provider":"maxmind"},{"continent":"NA","country":"US","state":"CA","city":"san francisco","normalizedCity":"san francisco","asn":6939,"latitude":37.72,"longitude":-122.44,"network":"hurricane electric llc","normalizedNetwork":"hurricane electric llc","provider":"fastly"}]})
```

**Comment by MartinKolarik** [comment]
If that's the output we'd get, then it should - that's exactly what's necessary.

**Comment by patrykcieszkowski** [comment]
Then why even bother formatting the message, why aren't we printing plain json?

**Comment by jimaek** [comment]
Just a reminder that logging logic and formatting will probably change when we choose an APM with log streaming and context matching

**Comment by MartinKolarik** [comment]
What I usually do is a short message to identify/categorize the error and then all relevant context as an object, so this mostly matches it.

**Comment by patrykcieszkowski** [comment]
this would be way better
```json
{"scope":"geoip","field":"normalizedCity","sources":[{"continent":"EU","country":"NL","city":"Naarden","normalizedCity":"naarden","asn":33915,"latitude":52.285,"longitude":5.1563,"network":"Vodafone Libertel B.V.","normalizedNetwork":"vodafone libertel b.v.","provider":"ipinfo"},{"continent":"EU","country":"NL","city":"Naarden","normalizedCity":"naarden","asn":33915,"latitude":52.2849,"longitude":5.1623,"network":"Ziggo","normalizedNetwork":"ziggo","provider":"maxmind"},{"continent":"EU","country":"NL","city":"naarden","normalizedCity":"naarden","asn":33915,"latitude":52.3,"longitude":5.13,"network":"vodafone libertel b.v.","normalizedNetwork":"vodafone libertel b.v.","provider":"fastly"}],"level":"error","message":"failed to find a correct value for a filed \"normalizedCity\"","timestamp":"2022-07-28 17:25:44"}
{"scope":"ws","message":"failed to collect probe metadata","level":"warn","timestamp":"2022-07-28 17:25:44"}
{"scope":"ws:error","message":"disconnecting client pJIn4qgl19tN1MTNAAAD for (failed to collect probe metadata) [::ffff:127.0.0.1]","level":"info","timestamp":"2022-07-28 17:25:44"}
```

**Comment by MartinKolarik** [comment]
I don't like full JSON output and even wrote a custom logger we use in all other projects, focused on pretty printing errors and metadata 😄 the logs to stdout should be readable for humans. For machine processing, there should be independent transport in whatever format the service wants.

**Comment by patrykcieszkowski** [comment]
But if we mix text with JSON (my previous example), we gonna end up with equally unreadable format anyway.

**Comment by MartinKolarik** [comment]
So if you wanted to dig into this more, I'd tell you to replace the logger, but right now I'm good with a quick fix of adding those fields. Later as @jimaek pointed out we'll set up a different APM and maybe overall change the logs setup too.

>  But if we mix text with JSON (my previous example), we gonna end up with equally unreadable format anyway.

Can it be pretty printed maybe? But even if no, it's better than full json because you don't always care about the extra context.

**Comment by patrykcieszkowski** [comment]
Adding them where?

**Comment by MartinKolarik** [comment]
To the output, in whatever format is easiest.

**Comment by patrykcieszkowski** [comment]
would this work?

```
[2022-07-28 17:38:17] [DEBUG] [1063238] [ws:error] failed to collect probe metadata
 info -> {"socketId":"Od3Iad7jz6GXryjVAAAF"}
 stack -> Error: failed to collect probe metadata
    at file:///home/patryk/projects/globalping/api/dist/lib/ws/middleware/probe-metadata.js:18:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Array.<anonymous> (file:///home/patryk/projects/globalping/api/dist/lib/ws/helper/error-handler.js:8:9)
[2022-07-28 17:38:17] [ERROR] [1063238] [geoip] failed to find a correct value for a filed "normalizedCity"
 field -> normalizedCity
 sources -> [{"continent":"EU","country":"PL","city":"Kraków","normalizedCity":"krakow","asn":43939,"latitude":50.0614,"longitude":19.9366,"network":"Netia SA","normalizedNetwork":"netia sa","provider":"ipinfo"},{"continent":"EU","country":"PL","city":"Krakow","normalizedCity":"krakow","asn":43939,"latitude":50.0585,"longitude":19.9342,"network":"Internetia","normalizedNetwork":"internetia","provider":"maxmind"},{"continent":"EU","country":"PL","city":"krakow","normalizedCity":"krakow","asn":43939,"latitude":50.08,"longitude":19.88,"network":"netia sa","normalizedNetwork":"netia sa","provider":"fastly"}]
```

**Comment by patrykcieszkowski** [comment]
Except, we probably don't even need to pass `sources` to the error metadata.

**Comment by MartinKolarik** [comment]
> Except, we probably don't even need to pass sources to the error metadata.

The issue we had after the last deploy is something where seeing `sources` in the output would give you an answer about what's wrong right away, instead of guessing.

> would this work?

Sure.

**Comment by patrykcieszkowski** [comment]
> The issue we had after the last deploy is something where seeing `sources` in the output would give you an answer about what's wrong right away, instead of guessing.

what if we were to shorten the `sources` object to the fields the query was working on?

```
[2022-07-28 17:46:37] [ERROR] [1063823] [geoip] failed to find a correct value for a filed "normalizedCity"
 field -> normalizedCity
 sources -> [{"provider":"ipinfo","normalizedCity":"milan"},{"provider":"maxmind","normalizedCity":""},{"provider":"fastly","normalizedCity":"ragusa"}]
```

**Comment by MartinKolarik** [comment]
Then already it wouldn't be useful in the previous case. You'd see `normalizedCity` is missing but wouldn't know if that's because the city/location wasn't resolved at all or some other bug. I know it looks verbose but you never really know in advance what detail will help you find the next bug.
