### ISSUE TITLE
Get logs from the probes

### ISSUE THREAD

**Issue by alexey-yarmosh** [jsdelivr/globalping#289]
We need to find the proper way to get logs from the probes. That is required to debug probe issues, monitor the probes state and get notified when JS error happens.
 
Requirements:
- error data should be logged in cases like:
    - https://github.com/jsdelivr/globalping-probe/blob/master/src/index.ts#L125
    - https://github.com/jsdelivr/globalping-probe/blob/master/src/lib/updater.ts
    - https://github.com/jsdelivr/globalping-probe/blob/master/src/command/ping-command.ts#L123
- logs from the probes should be safe for the API, need to make sure broken probe won't take all the newrelic storage space (probably should be combined with https://github.com/jsdelivr/globalping/issues/52 or another way of disabling the probes)
- most likely `winston-socket.io` should be used on the probe side, then log data to stdout on the API side.

**Comment by skapytek** [comment]
[2023-02-18 09:01:41] [ERROR] [687] [general] connection to API failed: websocket error
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

RequestError: Timeout awaiting 'request' for 15000ms
    at ClientRequest.<anonymous> (file:///app/node_modules/got/dist/source/core/index.js:760:61)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at TLSSocket.socketErrorListener (node:_http_client:496:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Timeout.timeoutHandler [as _onTimeout] (file:///app/node_modules/got/dist/source/core/timed-out.js:42:25)
    at listOnTimeout (node:internal/timers:566:11)
    at process.processTimers (node:internal/timers:507:7) {
  input: undefined,
  code: 'ETIMEDOUT',
  timings: {
    start: 1676710897020,
    socket: 1676710897023,
    lookup: undefined,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1676710912032,
    abort: undefined,
    phases: {
      wait: 3,
      dns: undefined,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 15012
    }
  },
  name: 'TimeoutError',
  options: Options {
    _unixOptions: undefined,
    _internals: {
      request: undefined,
      agent: { http: undefined, https: undefined, http2: undefined },
      h2session: undefined,
      decompress: true,
      timeout: {
        connect: undefined,
        lookup: undefined,
        read: undefined,
        request: 15000,
        response: undefined,
        secureConnect: undefined,
        send: undefined,
        socket: undefined
      },
      prefixUrl: '',
      body: undefined,
      form: undefined,
      json: undefined,
      cookieJar: undefined,
      ignoreInvalidCookies: false,
      searchParams: undefined,
      dnsLookup: undefined,
      dnsCache: undefined,
      context: {},
      hooks: {
        init: [],
        beforeRequest: [],
        beforeError: [],
        beforeRedirect: [],
        beforeRetry: [],
        afterResponse: []
      },
      followRedirect: true,
      maxRedirects: 10,
      cache: undefined,
      throwHttpErrors: true,
      username: '',
      password: '',
      http2: false,
      allowGetBody: false,
      headers: {
        'user-agent': 'got (https://github.com/sindresorhus/got)',
        accept: 'application/json',
        'accept-encoding': 'gzip, deflate, br'
      },
      methodRewriting: false,
      dnsLookupIpVersion: undefined,
      parseJson: [Function: parse],
      stringifyJson: [Function: stringify],
      retry: {
        limit: 2,
        methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
        statusCodes: [
          408, 413, 429, 500,
          502, 503, 504, 521,
          522, 524
        ],
        errorCodes: [
          'ETIMEDOUT',
          'ECONNRESET',
          'EADDRINUSE',
          'ECONNREFUSED',
          'EPIPE',
          'ENOTFOUND',
          'ENETUNREACH',
          'EAI_AGAIN'
        ],
        maxRetryAfter: undefined,
        calculateDelay: [Function: calculateDelay],
        backoffLimit: Infinity,
        noise: 100
      },
      localAddress: undefined,
      method: 'GET',
      createConnection: undefined,
      cacheOptions: {
        shared: undefined,
        cacheHeuristic: undefined,
        immutableMinTimeToLive: undefined,
        ignoreCargoCult: undefined
      },
      https: {
        alpnProtocols: undefined,
        rejectUnauthorized: undefined,
        checkServerIdentity: undefined,
        certificateAuthority: undefined,
        key: undefined,
        certificate: undefined,
        passphrase: undefined,
        pfx: undefined,
        ciphers: undefined,
        honorCipherOrder: undefined,
        minVersion: undefined,
        maxVersion: undefined,
        signatureAlgorithms: undefined,
        tlsSessionLifetime: undefined,
        dhparam: undefined,
        ecdhCurve: undefined,
        certificateRevocationLists: undefined
      },
      encoding: undefined,
      resolveBodyOnly: false,
      isStream: false,
      responseType: 'text',
      url: <ref *1> URL {
        [Symbol(context)]: URLContext {
          flags: 400,
          scheme: 'https:',
          username: '',
          password: '',
          host: 'api.github.com',
          port: null,
          path: [
            'repos',
            'jsdelivr',
            'globalping-probe',
            'releases',
            'latest'
          ],
          query: null,
          fragment: null
        },
        [Symbol(query)]: URLSearchParams {
          [Symbol(query)]: [],
          [Symbol(context)]: [Circular *1]
        }
      },
      pagination: {
        transform: [Function: transform],
        paginate: [Function: paginate],
        filter: [Function: filter],
        shouldContinue: [Function: shouldContinue],
        countLimit: Infinity,
        backoff: 0,
        requestLimit: 10000,
        stackAllItems: false
      },
      setHost: true,
      maxHeaderSize: undefined
    },
    _merging: false,
    _init: [ { timeout: { request: 15000 } } ]
  },
  event: 'request'
}

Node.js v18.13.0
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
Checking for the latest version
Current version 0.11.0
Latest version 0.13.0
Start self-update process
Self-update finished
[2023-02-18 09:02:35] [INFO] [696] [general] Start probe version 0.13.0 in a production mode
[2023-02-18 09:02:36] [DEBUG] [696] [general] connection to API established
[2023-02-18 09:02:36] [INFO] [696] [api:connect] connected from (Laakirchen, AT, EU) (lat: 47.9819 long: 13.8217)
[2023-02-18 09:41:15] [DEBUG] [696] [general] ping request VQROhRhOgJ2wRtOW received

**Comment by alexey-yarmosh** [comment]
Seems your probe still had version 0.11.0 on "2023-02-18", while 0.13.0 was deployed "2023-02-16". 0.11.0 don't have TimeoutError handling, that is why error occur.
The most interesting part is that self-update logic should update probes to the latest version within minutes, so 0.11.0 looks really strange, I'll review that and get back here. Thanks for the report!

**Comment by jimaek** [comment]
Current plan: Make it possible only for adopted probes via our upcoming dashboard. The user could view all probe logs and decide to send them to us if he wants. Maybe even offer an easy "generate debug info" button.
