### ISSUE TITLE
timeout reached while waiting for fetchSockets response

### ISSUE THREAD

**Issue by alexey-yarmosh** [jsdelivr/globalping#302]
There are fetchSockets timeout messages in logs. Using cluster might be a reason for that. Previously fetchSockets required data from the requester and 1 another instance, now from requester and 3 other workers. Need to define the real reason and fix that.

```log
[2023-03-22 10:31:35] [INFO] [30] [gateway] ws client ijUWrYBvU1gQwHIdAAKB connected from Singapore, SG [x.x.x.x - CacheNetworks, Inc.]
[2023-03-22 10:31:35] [INFO] [31] [gateway] ws client F0pttgoYtnzxJECTAAJd connected from Muong Lay, VN [x.x.x.x - VNPT Corp]
[2023-03-22 10:31:35] [INFO] [30] [gateway] ws client E0jn6UCiEcSPuR5mAAKD connected from Christchurch, NZ [x.x.x.x - Vodafone NZ Ltd.]
[2023-03-22 10:31:36] [INFO] [31] [ws:error] disconnecting client Y9yQ6-S7Tf96QX8jAACK for (timeout reached while waiting for fetchSockets response) [x.x.x.x]
[2023-03-22 10:31:36] [DEBUG] [31] [ws:error] timeout reached while waiting for fetchSockets response
Error: timeout reached while waiting for fetchSockets response
    at Timeout._onTimeout (/app/node_modules/@socket.io/redis-adapter/dist/index.js:559:28)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[2023-03-22 10:31:36] [INFO] [30] [ws:error] disconnecting client cJjeT3IIT6_zcfo4AACX for (timeout reached while waiting for fetchSockets response) [x.x.x.x]
[2023-03-22 10:31:36] [DEBUG] [30] [ws:error] timeout reached while waiting for fetchSockets response
Error: timeout reached while waiting for fetchSockets response
    at Timeout._onTimeout (/app/node_modules/@socket.io/redis-adapter/dist/index.js:559:28)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[2023-03-22 10:31:36] [INFO] [30] [ws:error] disconnecting client Qtpw1oERO-4GwYxWAACZ for (timeout reached while waiting for fetchSockets response) [x.x.x.x]
[2023-03-22 10:31:36] [DEBUG] [30] [ws:error] timeout reached while waiting for fetchSockets response
Error: timeout reached while waiting for fetchSockets response
    at Timeout._onTimeout (/app/node_modules/@socket.io/redis-adapter/dist/index.js:559:28)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[2023-03-22 10:31:37] [INFO] [31] [gateway] ws client QbIUf5AxgCoGfUBZAAJf connected from Bromley, GB [x.x.x.x - RHC Hosting]
[2023-03-22 10:31:37] [INFO] [30] [gateway] ws client FppNY2s0uWJdDHp6AAKF connected from Secaucus, US [x.x.x.x - GREEN FLOID LLC]
```

https://one.eu.newrelic.com/logger?account=3500053&begin=1678877640000&end=1679482440000&filters=%28domain%20%3D%20%27INFRA%27%20AND%20type%20%3D%20%27CONTAINER%27%29&state=589d8e0c-92b6-9fd9-7089-860e9605842f

**Comment by alexey-yarmosh** [comment]
default timeout is 5000ms
https://github.com/socketio/socket.io-redis-adapter#adapterpubclient-subclient-opts

**Comment by alexey-yarmosh** [comment]
Issues is still actual, it is just a question how many fetchSockets requests we do.

**Comment by MartinKolarik** [comment]
Fixed by https://github.com/jsdelivr/globalping/commit/de42d9c4758cadf6f302fac15a7310fe6eb4f643, which reduced the redis bandwidth by 85 %, and not a single timeout happened since. Will consider further improvements in #419 and #429.
